# Generated by Django 5.1.4 on 2026-06-06 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('crop_type', models.CharField(choices=[('banana', 'Banana'), ('coffee', 'Coffee')], max_length=10)),
                ('symptoms', models.JSONField(default=dict)),
                ('comments', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('disease', models.CharField(blank=True, choices=[('banana_bacterial_wilt', 'Banana Bacterial Wilt'), ('black_sigatoka', 'Black Sigatoka'), ('fusarium_wilt', 'Fusarium Wilt'), ('coffee_leaf_rust', 'Coffee Leaf Rust'), ('coffee_berry_disease', 'Coffee Berry Disease'), ('coffee_wilt_disease', 'Coffee Wilt Disease')], max_length=50, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('treatment', models.JSONField(default=list)),
                ('prevention', models.JSONField(default=list)),
                ('best_practices', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisory', to='reports.report')),
            ],
        ),
    ]
