# Generated by Django 5.1.4 on 2026-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='disease',
            field=models.CharField(blank=True, choices=[('banana_bacterial_wilt', 'Banana Bacterial Wilt'), ('coffee_leaf_rust', 'Coffee Leaf Rust')], max_length=50, null=True),
        ),
    ]
