# Generated by Django 5.1.4 on 2026-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='disease',
            field=models.CharField(blank=True, choices=[('banana_bacterial_wilt', 'Banana Bacterial Wilt'), ('banana_black_sigatoka', 'Black Sigatoka'), ('banana_fusarium_wilt', 'Fusarium Wilt (Panama Disease)'), ('banana_streak_virus', 'Banana Streak Virus'), ('coffee_leaf_rust', 'Coffee Leaf Rust'), ('coffee_berry_disease', 'Coffee Berry Disease'), ('coffee_wilt_disease', 'Coffee Wilt Disease'), ('coffee_leaf_miner', 'Coffee Leaf Miner')], max_length=50, null=True),
        ),
    ]
